from os.path import join as pjoin
import sys

DATA_DIR = "../data/"
RAW_DATA_DIR = pjoin(DATA_DIR, "raw")
INTERIM_DATA_DIR = pjoin(DATA_DIR, "interim")
PROCESSED_DATA_DIR = pjoin(DATA_DIR, "processed")

###############################################################################
# Raw Data
###############################################################################


###############################################################################
# Interim outputs
###############################################################################

PAPER_2003_2004 = pjoin(INTERIM_DATA_DIR, "paper_df_2003_2004.csv")
AUTHOR_2003_2004 = pjoin(INTERIM_DATA_DIR, "author_df_2003_2004.csv")
PAPER_2005_2013 = pjoin(INTERIM_DATA_DIR, "paper_df_2005_2013.csv")
AUTHOR_2005_2013 = pjoin(INTERIM_DATA_DIR, "author_df_2005_2013.csv")
SESSION_2014_2018 = pjoin(INTERIM_DATA_DIR, 'session_df_2014_2018.csv')
AUTHOR_2014_2018 = pjoin(INTERIM_DATA_DIR, 'author_df_2014_2018.csv')
PAPER_2014_2018 = pjoin(INTERIM_DATA_DIR, 'paper_df_2014_2018.csv')
INTERACTIVE_SESSION_2014_2018 = pjoin(INTERIM_DATA_DIR, 'interactive_session_df_2014_2018.csv')
INTERACTIVE_AUTHOR_2014_2018 = pjoin(INTERIM_DATA_DIR, 'interactive_author_df_2014_2018.csv')
INTERACTIVE_PAPER_2014_2018 = pjoin(INTERIM_DATA_DIR, 'interactive_paper_df_2014_2018.csv')


###############################################################################
# Processed outputs
###############################################################################
PAPER_DF = pjoin(PROCESSED_DATA_DIR, 'paper_df.csv')
AUTHOR_DF = pjoin(PROCESSED_DATA_DIR, 'author_df.csv')
SESSION_DF = pjoin(PROCESSED_DATA_DIR, 'session_df.csv')

###############################################################################
# Workflows
###############################################################################

rule all:
    input:
        PAPER_2003_2004,
        AUTHOR_2003_2004,
        PAPER_2005_2013,
        AUTHOR_2005_2013,
        SESSION_2014_2018,
        AUTHOR_2014_2018,
        PAPER_2014_2018,
        INTERACTIVE_SESSION_2014_2018,
        INTERACTIVE_AUTHOR_2014_2018,
        INTERACTIVE_PAPER_2014_2018,
        PAPER_DF,
        AUTHOR_DF,
        SESSION_DF,

rule scrape_03_04:
    output: 
        PAPER_2003_2004,
        AUTHOR_2003_2004,
    shell: "python scripts/scrape_2003_2004.py {output}"

rule scrape_2005_2013:
    output: 
        PAPER_2005_2013,
        AUTHOR_2005_2013,
    shell: "python scripts/scrape_2005_2013.py {output}"

rule scrape_2014_onward_paper:
    output: 
        SESSION_2014_2018,
        AUTHOR_2014_2018,
        PAPER_2014_2018,
    shell: "python scripts/scrape_2014_onward_paper.py {output}"

rule scrape_2014_onward_interactive_paper:
    output: 
        INTERACTIVE_SESSION_2014_2018,
        INTERACTIVE_AUTHOR_2014_2018,
        INTERACTIVE_PAPER_2014_2018,
    shell: "python scripts/scrape_2014_onward_interactive_paper.py {output}"

rule combine_all_data:
    input:
        PAPER_2003_2004,
        PAPER_2005_2013,
        PAPER_2014_2018,
        INTERACTIVE_PAPER_2014_2018,
        AUTHOR_2003_2004,
        AUTHOR_2005_2013,
        AUTHOR_2014_2018,
        INTERACTIVE_AUTHOR_2014_2018,
        SESSION_2014_2018,
        INTERACTIVE_SESSION_2014_2018
    output: 
        PAPER_DF,
        AUTHOR_DF,
        SESSION_DF,
    shell: "python scripts/combine_all_data.py {input} {output}"
